services:
  - type: web
    name: shoplit
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn shoplit.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shoplit.settings.prod
