# Generated by Django 5.1.4 on 2025-01-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
